// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `pdm.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.lpmas.pdm.component;

public final class PdmServiceHolder extends Ice.ObjectHolderBase<PdmService> {
	public PdmServiceHolder() {
	}

	public PdmServiceHolder(PdmService value) {
		this.value = value;
	}

	public void patch(Ice.Object v) {
		if (v == null || v instanceof PdmService) {
			value = (PdmService) v;
		} else {
			IceInternal.Ex.throwUOE(type(), v);
		}
	}

	public String type() {
		return _PdmServiceDisp.ice_staticId();
	}
}
