// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `pdm.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.lpmas.pdm.component;

public interface PdmService extends Ice.Object, _PdmServiceOperations, _PdmServiceOperationsNC {
	public static final String ice_staticId = "::com::lpmas::pdm::component::PdmService";

	public static final long serialVersionUID = 1937347629L;
}
